// Code generated by protoc-gen-go. DO NOT EDIT.
// source: poki.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	poki.proto

It has these top-level messages:
	Document
	DocumentRevision
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Document struct {
	Id      string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Payload *google_protobuf.Any `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
}

func (m *Document) Reset()                    { *m = Document{} }
func (m *Document) String() string            { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()               {}
func (*Document) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Document) GetPayload() *google_protobuf.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type DocumentRevision struct {
	Rev string `protobuf:"bytes,1,opt,name=rev" json:"rev,omitempty"`
}

func (m *DocumentRevision) Reset()                    { *m = DocumentRevision{} }
func (m *DocumentRevision) String() string            { return proto.CompactTextString(m) }
func (*DocumentRevision) ProtoMessage()               {}
func (*DocumentRevision) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DocumentRevision) GetRev() string {
	if m != nil {
		return m.Rev
	}
	return ""
}

func init() {
	proto.RegisterType((*Document)(nil), "Document")
	proto.RegisterType((*DocumentRevision)(nil), "DocumentRevision")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Poki service

type PokiClient interface {
	CreateDoc(ctx context.Context, in *Document, opts ...grpc.CallOption) (*DocumentRevision, error)
}

type pokiClient struct {
	cc *grpc.ClientConn
}

func NewPokiClient(cc *grpc.ClientConn) PokiClient {
	return &pokiClient{cc}
}

func (c *pokiClient) CreateDoc(ctx context.Context, in *Document, opts ...grpc.CallOption) (*DocumentRevision, error) {
	out := new(DocumentRevision)
	err := grpc.Invoke(ctx, "/Poki/CreateDoc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Poki service

type PokiServer interface {
	CreateDoc(context.Context, *Document) (*DocumentRevision, error)
}

func RegisterPokiServer(s *grpc.Server, srv PokiServer) {
	s.RegisterService(&_Poki_serviceDesc, srv)
}

func _Poki_CreateDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Document)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokiServer).CreateDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Poki/CreateDoc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokiServer).CreateDoc(ctx, req.(*Document))
	}
	return interceptor(ctx, in, info, handler)
}

var _Poki_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Poki",
	HandlerType: (*PokiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDoc",
			Handler:    _Poki_CreateDoc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poki.proto",
}

func init() { proto.RegisterFile("poki.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc8, 0xcf, 0xce,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4c, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07,
	0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x13, 0xf3, 0x2a, 0x21, 0x52, 0x4a, 0x5e, 0x5c, 0x1c, 0x2e, 0xf9,
	0xc9, 0xa5, 0xb9, 0xa9, 0x79, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x7a, 0x5c, 0xec, 0x05, 0x89, 0x95, 0x39, 0xf9, 0x89,
	0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x22, 0x7a, 0x10, 0x83, 0xf4, 0x60, 0x06, 0xe9,
	0x39, 0xe6, 0x55, 0x06, 0xc1, 0x14, 0x29, 0xa9, 0x70, 0x09, 0xc0, 0xcc, 0x0a, 0x4a, 0x2d, 0xcb,
	0x2c, 0xce, 0xcc, 0xcf, 0x13, 0x12, 0xe0, 0x62, 0x2e, 0x4a, 0x2d, 0x83, 0x1a, 0x0a, 0x62, 0x1a,
	0x19, 0x72, 0xb1, 0x04, 0xe4, 0x67, 0x67, 0x0a, 0x69, 0x72, 0x71, 0x3a, 0x17, 0xa5, 0x26, 0x96,
	0xa4, 0xba, 0xe4, 0x27, 0x0b, 0x71, 0xea, 0xc1, 0x74, 0x4a, 0x09, 0xea, 0xa1, 0x1b, 0xe2, 0x24,
	0x13, 0x25, 0x95, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x5f, 0x90, 0x9f,
	0x5d, 0x5c, 0x92, 0x98, 0x02, 0xa2, 0x33, 0xf5, 0x0b, 0x92, 0x92, 0xd8, 0xc0, 0xae, 0x31, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xaf, 0x29, 0x72, 0xf2, 0x00, 0x00, 0x00,
}
