// Code generated by protoc-gen-go. DO NOT EDIT.
// source: poki.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	poki.proto

It has these top-level messages:
	Post
	Rev
	PathRev
	PostRev
	CreateResponse
	ReadResponse
	UpdateResponse
	DeleteResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Post struct {
	Raw  []byte         `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Meta *Post_MetaData `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	Path string         `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
}

func (m *Post) Reset()                    { *m = Post{} }
func (m *Post) String() string            { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()               {}
func (*Post) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Post) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

func (m *Post) GetMeta() *Post_MetaData {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Post) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Post_MetaData struct {
	Updated *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=updated" json:"updated,omitempty"`
	Title   string                     `protobuf:"bytes,2,opt,name=Title" json:"Title,omitempty"`
}

func (m *Post_MetaData) Reset()                    { *m = Post_MetaData{} }
func (m *Post_MetaData) String() string            { return proto.CompactTextString(m) }
func (*Post_MetaData) ProtoMessage()               {}
func (*Post_MetaData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Post_MetaData) GetUpdated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

func (m *Post_MetaData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Rev struct {
	RevisionId string `protobuf:"bytes,1,opt,name=revision_id,json=revisionId" json:"revision_id,omitempty"`
}

func (m *Rev) Reset()                    { *m = Rev{} }
func (m *Rev) String() string            { return proto.CompactTextString(m) }
func (*Rev) ProtoMessage()               {}
func (*Rev) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Rev) GetRevisionId() string {
	if m != nil {
		return m.RevisionId
	}
	return ""
}

type PathRev struct {
	Path       string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	RevisionId string `protobuf:"bytes,2,opt,name=revision_id,json=revisionId" json:"revision_id,omitempty"`
}

func (m *PathRev) Reset()                    { *m = PathRev{} }
func (m *PathRev) String() string            { return proto.CompactTextString(m) }
func (*PathRev) ProtoMessage()               {}
func (*PathRev) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PathRev) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PathRev) GetRevisionId() string {
	if m != nil {
		return m.RevisionId
	}
	return ""
}

type PostRev struct {
	Rev  *Rev  `protobuf:"bytes,1,opt,name=rev" json:"rev,omitempty"`
	Post *Post `protobuf:"bytes,2,opt,name=post" json:"post,omitempty"`
}

func (m *PostRev) Reset()                    { *m = PostRev{} }
func (m *PostRev) String() string            { return proto.CompactTextString(m) }
func (*PostRev) ProtoMessage()               {}
func (*PostRev) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PostRev) GetRev() *Rev {
	if m != nil {
		return m.Rev
	}
	return nil
}

func (m *PostRev) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type CreateResponse struct {
	Rev *Rev `protobuf:"bytes,1,opt,name=rev" json:"rev,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateResponse) GetRev() *Rev {
	if m != nil {
		return m.Rev
	}
	return nil
}

type ReadResponse struct {
	PostRev *PostRev `protobuf:"bytes,1,opt,name=post_rev,json=postRev" json:"post_rev,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadResponse) GetPostRev() *PostRev {
	if m != nil {
		return m.PostRev
	}
	return nil
}

type UpdateResponse struct {
	Rev *Rev `protobuf:"bytes,1,opt,name=rev" json:"rev,omitempty"`
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateResponse) GetRev() *Rev {
	if m != nil {
		return m.Rev
	}
	return nil
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*Post)(nil), "pokstad.poki.Post")
	proto.RegisterType((*Post_MetaData)(nil), "pokstad.poki.Post.MetaData")
	proto.RegisterType((*Rev)(nil), "pokstad.poki.Rev")
	proto.RegisterType((*PathRev)(nil), "pokstad.poki.PathRev")
	proto.RegisterType((*PostRev)(nil), "pokstad.poki.PostRev")
	proto.RegisterType((*CreateResponse)(nil), "pokstad.poki.CreateResponse")
	proto.RegisterType((*ReadResponse)(nil), "pokstad.poki.ReadResponse")
	proto.RegisterType((*UpdateResponse)(nil), "pokstad.poki.UpdateResponse")
	proto.RegisterType((*DeleteResponse)(nil), "pokstad.poki.DeleteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Poki service

type PokiClient interface {
	Create(ctx context.Context, in *Post, opts ...grpc.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *Post, opts ...grpc.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *PathRev, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *PathRev, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type pokiClient struct {
	cc *grpc.ClientConn
}

func NewPokiClient(cc *grpc.ClientConn) PokiClient {
	return &pokiClient{cc}
}

func (c *pokiClient) Create(ctx context.Context, in *Post, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/pokstad.poki.Poki/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokiClient) Read(ctx context.Context, in *Post, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := grpc.Invoke(ctx, "/pokstad.poki.Poki/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokiClient) Update(ctx context.Context, in *PathRev, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := grpc.Invoke(ctx, "/pokstad.poki.Poki/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokiClient) Delete(ctx context.Context, in *PathRev, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/pokstad.poki.Poki/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Poki service

type PokiServer interface {
	Create(context.Context, *Post) (*CreateResponse, error)
	Read(context.Context, *Post) (*ReadResponse, error)
	Update(context.Context, *PathRev) (*UpdateResponse, error)
	Delete(context.Context, *PathRev) (*DeleteResponse, error)
}

func RegisterPokiServer(s *grpc.Server, srv PokiServer) {
	s.RegisterService(&_Poki_serviceDesc, srv)
}

func _Poki_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokiServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokstad.poki.Poki/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokiServer).Create(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poki_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokiServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokstad.poki.Poki/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokiServer).Read(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poki_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathRev)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokiServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokstad.poki.Poki/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokiServer).Update(ctx, req.(*PathRev))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poki_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathRev)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokiServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokstad.poki.Poki/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokiServer).Delete(ctx, req.(*PathRev))
	}
	return interceptor(ctx, in, info, handler)
}

var _Poki_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pokstad.poki.Poki",
	HandlerType: (*PokiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Poki_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Poki_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Poki_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Poki_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poki.proto",
}

func init() { proto.RegisterFile("poki.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x57, 0xda, 0xd2, 0xac, 0xaf, 0xd5, 0x18, 0x16, 0x13, 0x55, 0x28, 0x5a, 0x65, 0xa4, 0xa9,
	0xda, 0xc1, 0x41, 0x05, 0x2e, 0x1c, 0x10, 0x82, 0x49, 0x88, 0x03, 0x68, 0xb2, 0xc6, 0x0e, 0x08,
	0xa9, 0x72, 0xc9, 0xa3, 0xb5, 0xda, 0xc6, 0x56, 0xe2, 0x86, 0xc3, 0xc4, 0x85, 0xaf, 0xc0, 0x67,
	0xe1, 0x93, 0x70, 0xe7, 0xc4, 0x07, 0x41, 0xb6, 0x13, 0xba, 0x74, 0x3d, 0x6c, 0xa7, 0x38, 0x7e,
	0xef, 0xf7, 0xe7, 0xfd, 0xf2, 0x02, 0xa0, 0xd5, 0x42, 0x32, 0x9d, 0x29, 0xa3, 0x48, 0x4f, 0xab,
	0x45, 0x6e, 0x44, 0xc2, 0xec, 0x5d, 0x74, 0x34, 0x53, 0x6a, 0xb6, 0xc4, 0xd8, 0xd5, 0xa6, 0xeb,
	0xaf, 0xb1, 0x91, 0x2b, 0xcc, 0x8d, 0x58, 0x69, 0xdf, 0x1e, 0x0d, 0xca, 0x06, 0xa1, 0x65, 0x2c,
	0xd2, 0x54, 0x19, 0x61, 0xa4, 0x4a, 0x73, 0x5f, 0xa5, 0xbf, 0x02, 0x68, 0x9d, 0xa9, 0xdc, 0x90,
	0x03, 0x68, 0x66, 0xe2, 0x5b, 0x3f, 0x18, 0x06, 0xa3, 0x1e, 0xb7, 0x47, 0x12, 0x43, 0x6b, 0x85,
	0x46, 0xf4, 0x1b, 0xc3, 0x60, 0xd4, 0x1d, 0x3f, 0x64, 0x57, 0x65, 0x99, 0xc5, 0xb0, 0xf7, 0x68,
	0xc4, 0xa9, 0x30, 0x82, 0xbb, 0x46, 0x42, 0xa0, 0xa5, 0x85, 0x99, 0xf7, 0x9b, 0xc3, 0x60, 0xd4,
	0xe1, 0xee, 0x1c, 0x5d, 0xc0, 0x5e, 0xd5, 0x45, 0x9e, 0x41, 0xb8, 0xd6, 0x89, 0x30, 0x98, 0x38,
	0x99, 0xee, 0x38, 0x62, 0xde, 0x1b, 0xab, 0xcc, 0xb3, 0xf3, 0xca, 0x3c, 0xaf, 0x5a, 0xc9, 0x7d,
	0xb8, 0x73, 0x2e, 0xcd, 0x12, 0x9d, 0x8f, 0x0e, 0xf7, 0x2f, 0xf4, 0x18, 0x9a, 0x1c, 0x0b, 0x72,
	0x04, 0xdd, 0x0c, 0x0b, 0x99, 0x4b, 0x95, 0x4e, 0xa4, 0xa7, 0xed, 0x70, 0xa8, 0xae, 0xde, 0x25,
	0xf4, 0x25, 0x84, 0x67, 0xc2, 0xcc, 0x6d, 0x6f, 0x65, 0x2f, 0xd8, 0xd8, 0xdb, 0xc6, 0x37, 0xae,
	0xe1, 0x2f, 0x20, 0xb4, 0xa3, 0x5a, 0xfc, 0x63, 0x68, 0x66, 0x58, 0x94, 0xd6, 0xef, 0xd5, 0xe3,
	0xe0, 0x58, 0x70, 0x5b, 0x25, 0xc7, 0xd0, 0xd2, 0x2a, 0x37, 0x65, 0x68, 0xe4, 0x7a, 0x68, 0xdc,
	0xd5, 0xe9, 0x73, 0xd8, 0x7f, 0x93, 0xa1, 0x30, 0xc8, 0x31, 0xd7, 0x2a, 0xcd, 0xf1, 0x46, 0xf4,
	0xf4, 0x15, 0xf4, 0x38, 0x8a, 0xe4, 0x3f, 0xe8, 0x09, 0xec, 0x59, 0xba, 0xc9, 0x06, 0x79, 0xb8,
	0x43, 0x12, 0x0b, 0x1e, 0x6a, 0x7f, 0xb0, 0xc2, 0x1f, 0x5d, 0xb2, 0xb7, 0x13, 0x3e, 0x80, 0xfd,
	0x53, 0x5c, 0xe2, 0x06, 0x36, 0xfe, 0xd3, 0xb0, 0x9b, 0xb3, 0x90, 0xe4, 0x03, 0xb4, 0xfd, 0x28,
	0x64, 0xc7, 0xb8, 0xd1, 0xa0, 0x7e, 0x57, 0x1f, 0x9a, 0x92, 0x1f, 0xbf, 0xff, 0xfe, 0x6c, 0xf4,
	0x68, 0x18, 0x5f, 0xda, 0xef, 0xf1, 0xfd, 0x45, 0x70, 0x42, 0xde, 0x42, 0xcb, 0xce, 0xb8, 0x93,
	0x2d, 0xda, 0xb6, 0xb7, 0xc9, 0x82, 0xde, 0x75, 0x5c, 0x1d, 0x52, 0x71, 0x91, 0x09, 0xb4, 0xfd,
	0xa8, 0x64, 0x3b, 0x14, 0xbf, 0x11, 0xdb, 0xde, 0xea, 0xb9, 0xd0, 0xa1, 0xe3, 0x8b, 0xa2, 0xc3,
	0x92, 0x2f, 0xbe, 0xbc, 0xb2, 0x2a, 0xce, 0xe9, 0x67, 0x68, 0xfb, 0x50, 0x6e, 0x28, 0x50, 0x4f,
	0x90, 0x3e, 0x72, 0x02, 0x0f, 0x4e, 0x76, 0x0b, 0xbc, 0x1e, 0x7c, 0x8a, 0x66, 0xd2, 0xcc, 0xd7,
	0x53, 0xf6, 0x45, 0xad, 0xe2, 0x92, 0xc8, 0x3e, 0x65, 0xac, 0xa7, 0xd3, 0xb6, 0xfb, 0x67, 0x9e,
	0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x31, 0x50, 0x6d, 0x3c, 0x1a, 0x04, 0x00, 0x00,
}
